# This is a basic workflow to help you get started with Actions

name: Unit Tests & Linting

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  testing:
    name: ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toxenv: [flake8, unit]

    env:
      TOXENV: ${{ matrix.toxenv }}
      PYTEST_ADDOPTS: "-v --color=yes"
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with: 
          python-version: '3.8'
          
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Install python dependencies
        run: |
          sudo apt-get install libsasl2-dev
          pip install --user --upgrade pip
          pip install tox
          pip --version
          tox --version
      
      - name: Run tox
        run: tox
